version: '2'
services:
    app:
        build:
            context: .
        restart: always
        links:
            - redis
    nginx:
        build: ./nginx/
        restart: always
        links:
            - app
        ports:
            - "5000:80"
    redis:
        image: redis
        restart: always
        volumes:
            - redisdata:/data
        expose:
            - "6379"

volumes:
    redisdata:
        external:
            name: mykiredis
